changing back to failing if not on main + uncommenting publishing job

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -13,6 +13,7 @@ jobs:
         uses: actions/checkout@v4
 
       # Gets commit of tag and checks if main is an ancestor of tag commit (e.g. tag is on main branch)
+      # Workflow will fail on this step if commit is not on main
       - name: Verify tag commit is on main branch
         run: |
           git fetch --tags origin
@@ -23,7 +24,7 @@ jobs:
 
           if ! git merge-base --is-ancestor origin/main "$TAG_COMMIT"; then
             echo "Tag commit is not on main branch. Exiting."
-            exit 0
+            exit 1
           fi
 
       - name: Set up Node.js
@@ -42,11 +43,11 @@ jobs:
         env:
           CI: true
 
-# Commented out workflow for publishing extension, testing
-#      - name: Package and publish VS Code extension
-#        if: ${{ success() }}
-#        env:
-#          VSCE_PAT: ${{ secrets.VSCE_PAT }}
-#        run: |
-#          npm install -g @vscode/vsce
-#          vsce publish --pat $VSCE_PAT
+# Job for publishing extension - currently need to add the $VSCE_PAT secret still
+      - name: Package and publish VS Code extension
+        if: ${{ success() }}
+        env:
+          VSCE_PAT: ${{ secrets.VSCE_PAT }}
+        run: |
+          npm install -g @vscode/vsce
+          vsce publish --pat $VSCE_PAT
